// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/customer-intelligence/CleanLight.tsx": () => import("../components/mockups/customer-intelligence/CleanLight.tsx"),
  "./components/mockups/customer-intelligence/DarkPro.tsx": () => import("../components/mockups/customer-intelligence/DarkPro.tsx")
};
